# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='назва країни')),
                ('egd_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='країна в EGD')),
            ],
            options={
                'verbose_name_plural': 'країни',
                'verbose_name': 'країна',
            },
        ),
    ]
