# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UGD', '0002_club'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=6, verbose_name='ранг')),
                ('demotion', models.PositiveIntegerField(blank=True, null=True, verbose_name='нижня межа')),
                ('promotion', models.PositiveIntegerField(blank=True, null=True, verbose_name='верхня межа')),
                ('egd_grade', models.CharField(blank=True, max_length=3, null=True, verbose_name='ранг')),
            ],
        ),
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name': 'клуб', 'verbose_name_plural': 'клуби'},
        ),
        migrations.AlterField(
            model_name='club',
            name='egd_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='клуб в EGD'),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='назва клубу'),
        ),
    ]
