# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UGD', '0003_auto_20170113_1312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rank',
            options={'verbose_name': 'ранг', 'verbose_name_plural': 'ранги'},
        ),
    ]
