# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UGD', '0004_auto_20170113_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='спортивний розряд')),
                ('abbreviate', models.CharField(max_length=20, verbose_name='абревіатура')),
            ],
            options={
                'verbose_name_plural': 'спортивні розряди',
                'verbose_name': 'спортивний розряд',
            },
        ),
    ]
