# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-13 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UGD', '0005_localrank'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='прізвище')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="ім'я")),
                ('rating', models.PositiveIntegerField(blank=True, null=True, verbose_name='рейтинг УФГО')),
                ('sex', models.NullBooleanField(default=None, verbose_name='стать')),
                ('ufgo_member', models.BooleanField(default=False, verbose_name='Член УФГО')),
                ('egd_last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='прізвище у EGD')),
                ('egd_first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name="ім'я у EGD")),
                ('egd_rating', models.PositiveIntegerField(blank=True, null=True, verbose_name='Єврорейтинг')),
                ('egd_place', models.PositiveIntegerField(blank=True, null=True, verbose_name='Єврорейтинг')),
                ('egd_pin', models.CharField(blank=True, max_length=8, null=True, verbose_name='Код гравця у EGD')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UGD.Club', verbose_name='клуб')),
                ('local_rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UGD.LocalRank', verbose_name='спортивний розряд')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UGD.Rank', verbose_name='ранг')),
            ],
            options={
                'verbose_name': 'гравець',
                'verbose_name_plural': 'гравці',
            },
        ),
    ]
