# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-01-15 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UGD', '0006_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='назва турніру')),
                ('date_begin', models.DateField(blank=True, null=True, verbose_name='дата початку')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='дата завершення')),
                ('ranked', models.NullBooleanField(choices=[(False, 'Ні'), (True, 'Так')], default=True, max_length=1, verbose_name='рейтинговий')),
                ('egd_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='назва турніру в EGD')),
                ('egd_class', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True, verbose_name='клас турніру в EGD')),
                ('egd_code', models.CharField(blank=True, max_length=8, null=True, verbose_name='код турніру в EGD')),
                ('table', models.FileField(blank=True, null=True, upload_to='uploads/tournaments/', verbose_name='турнірна таблиця')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UGD.Club', verbose_name='місто')),
            ],
            options={
                'verbose_name': 'турнір',
                'verbose_name_plural': 'турніри',
            },
        ),
        migrations.AlterField(
            model_name='player',
            name='egd_place',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Місце у EGD'),
        ),
        migrations.AlterField(
            model_name='player',
            name='sex',
            field=models.NullBooleanField(choices=[(False, '♀'), (True, '♂')], default=None, verbose_name='стать'),
        ),
        migrations.AlterField(
            model_name='rank',
            name='egd_grade',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='ранг у EGD'),
        ),
    ]
