# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UGD', '0008_auto_20170116_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairing',
            name='round_skip',
            field=models.BooleanField(default=False, verbose_name='Пропуск туру'),
        ),
    ]
