# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UGD', '0009_pairing_round_skip'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='назва міста')),
                ('egd_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='місто в EGD')),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='UGD.Country', verbose_name='країна')),
            ],
        ),
        migrations.AlterField(
            model_name='tournament',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UGD.City', verbose_name='місто'),
        ),
    ]
