# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-18 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UGD', '0010_auto_20170118_1144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'місто', 'verbose_name_plural': 'міста'},
        ),
    ]
