# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-01-23 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UGD', '0012_auto_20170120_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='country',
        ),
        migrations.RemoveField(
            model_name='player',
            name='club',
        ),
        migrations.AddField(
            model_name='player',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UGD.City', verbose_name='клуб'),
        ),
        migrations.DeleteModel(
            name='Club',
        ),
    ]
