# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UGD', '0014_auto_20170123_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активний'),
        ),
        migrations.AlterField(
            model_name='player',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UGD.City', verbose_name='місто'),
        ),
        migrations.AlterField(
            model_name='player',
            name='local_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UGD.LocalRank', verbose_name='розряд'),
        ),
        migrations.AlterField(
            model_name='player',
            name='rating',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='рейтинг'),
        ),
    ]
