# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-03 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UGD', '0015_auto_20170126_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='place',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='позиція в рейтингу'),
        ),
    ]
