# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-03 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UGD', '0016_player_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='egd_first_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='egd_last_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='egd_place',
        ),
        migrations.RemoveField(
            model_name='player',
            name='egd_rating',
        ),
    ]
