# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-03 09:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UGD', '0017_auto_20170203_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='egd_class',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='egd_name',
        ),
        migrations.RemoveField(
            model_name='tournamentplayer',
            name='egd_rating_finish',
        ),
        migrations.RemoveField(
            model_name='tournamentplayer',
            name='egd_rating_start',
        ),
    ]
