# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-11 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UGD', '0018_auto_20170203_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairing',
            name='game_result',
            field=models.NullBooleanField(verbose_name='перемога'),
        ),
    ]
