# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-12 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UGD', '0019_auto_20170212_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentplayer',
            name='rating_finish',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='R2'),
        ),
        migrations.AlterField(
            model_name='tournamentplayer',
            name='rating_start',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='R1'),
        ),
    ]
