# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-18 11:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UGD', '0020_auto_20170212_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairing',
            name='tournament_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairing_player', to='UGD.TournamentPlayer', verbose_name='гравець'),
        ),
        migrations.AlterField(
            model_name='pairing',
            name='tournament_player_opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pairing_opponent', to='UGD.TournamentPlayer', verbose_name='суперник'),
        ),
    ]
