# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-24 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UGD', '0021_auto_20170218_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pairing',
            name='tournament_player_opponent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pairing_opponent', to='UGD.TournamentPlayer', verbose_name='суперник'),
        ),
    ]
