# -*- coding: utf-8 -*-
# Generated by Django 1.11a1 on 2017-02-26 09:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UGD', '0023_auto_20170224_2104'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tournamentplayer',
            table='participant',
        ),
    ]
